### Part 1

In [1]:
import numpy as np
from calcule import Calcule

Number of consecutive numbers

In [2]:
l = [4,2,3,3,0,89,89,89,10,4]
Calcule.consecutive(l)

3

In [3]:
f = set(l)
f.update([1, 2, 3])

In [4]:
f

{0, 1, 2, 3, 4, 10, 89}

Sum of sequence

In [5]:
Calcule.suma(15)

68.0

In [8]:
%%timeit

Calcule.suma(n = 1e+9)

3 µs ± 25 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Part 2

In [9]:
from graf import Graf

In [10]:
M = np.array([[1, 1, 0, 0, 1, 0],
              [1, 0, 1, 0, 1, 0],
              [0, 1, 0, 1, 0, 0],
              [0, 0, 1, 0, 1, 1],
              [1, 1, 0, 1, 0, 0],
              [0, 0, 0, 1, 0, 0]])

In [11]:
G = Graf()
G.set_adiacenta(M)

Get adjacency matrix of a graph

In [12]:
G.get_adiacenta()

array([[1, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]])

Get incidence matrix of a graph

In [13]:
G.get_incidenta()

array([[1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

Get kirhoff matrix of a graph

In [14]:
G.get_kirhoff()

array([[ 3, -1,  0,  0, -1,  0],
       [-1,  3, -1,  0, -1,  0],
       [ 0, -1,  2, -1,  0,  0],
       [ 0,  0, -1,  3, -1, -1],
       [-1, -1,  0, -1,  3,  0],
       [ 0,  0,  0, -1,  0,  1]])

Merge 2 graphs

In [15]:
M_2 = np.array([[0, 1, 1],
              [1, 0, 1],
              [1, 1, 0]])

In [16]:
A = Graf()
A.set_adiacenta(M)
B = Graf()
B.set_adiacenta(M_2)

In [17]:
C = Graf.get_united_graph(A, B)
C.get_adiacenta()

array([[1, 1, 0, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0]])

Try weighted graph

In [18]:
M = np.array([[0, 2, 1, 5],
              [2, 0, 0, 0],
              [1, 0, 0, 6],
              [5, 0, 6, 0]])

In [19]:
G = Graf()
G.set_adiacenta(M)

In [20]:
G.get_adiacenta()

array([[0, 2, 1, 5],
       [2, 0, 0, 0],
       [1, 0, 0, 6],
       [5, 0, 6, 0]])

In [21]:
G.get_incidenta()

array([[2, 1, 5, 0],
       [2, 0, 0, 0],
       [0, 1, 0, 6],
       [0, 0, 5, 6]])

In [22]:
G.get_kirhoff()

array([[ 8, -2, -1, -5],
       [-2,  2,  0,  0],
       [-1,  0,  7, -6],
       [-5,  0, -6, 11]])

Realization of Prim algorithm

In [23]:
Prim = np.array([[ 0, 27,  0,  0,  0,  0, 21], 
              [27,  0, 14, 13, 18,  0, 16], 
              [ 0, 14,  0, 14,  0,  0,  0], 
              [ 0, 13, 14,  0, 24,  0,  0],
              [ 0, 18,  0, 24,  0, 29,  0], 
              [ 0,  0,  0,  0, 29,  0, 22], 
              [21, 16,  0,  0,  0, 22,  0]])

In [24]:
P = Graf()
P.set_adiacenta(Prim)
P.get_arbore_partial_min()

array([[21.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 16., 13., 14., 18.,  0.],
       [ 0.,  0.,  0., 14.,  0.,  0.],
       [ 0.,  0., 13.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 22.],
       [21., 16.,  0.,  0.,  0., 22.]])

Additional

In [7]:
# suma3 is for 1,2,2,3,4,4,4,4,5,6,6,6,6,6
def s_even(n):
    return 2*n*(n + 1)*(2*n + 1)/3
def suma3(n: int) -> int:
    root = np.sqrt(n)
    if root.is_integer():
        a = 2*root - 1
    else: 
        a = 2*np.floor(root)
        
    if a % 2 == 0:
        s = (a/2) ** 2
        s += s_even(a/2 - 1)
        even = n - (a/2)*(a/2 - 1) - a/2
        s += even * a
    else:
        s = ((a + 1)/2) ** 2
        s += s_even((a-1)/2)
        n_even_numbers = 0
    return s

In [11]:
%%timeit

suma3(1e+6)

4.45 µs ± 71 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
